### ISSUE TITLE
【添加应用】添加免费VPN服务器程序——萤火虫

### ISSUE THREAD

**Issue by Safe3** [okxlin/appstore#1155]
项目地址：https://github.com/Safe3/firefly

软件介绍：
最简单易用的WireGuard服务器之一。内网穿透、异地组网、远程办公。

界面展示：
![image](https://raw.githubusercontent.com/Safe3/firefly/main/firefly.png)

**Comment by okxlin** [comment]
好的大佬😁，晚些添加

**Comment by Safe3** [comment]
不错不错，响应速度值得称赞！
