### ISSUE TITLE
可以增加个硬盘健康检测之类的应用吗？

### ISSUE THREAD

**Issue by sameceo** [okxlin/appstore#1239]
可以增加个硬盘健康检测之类的应用吗？

**Comment by okxlin** [comment]
可以推荐docker镜像，没有具体的也不好确定。最好项目官方就有现成镜像的。

**Comment by sameceo** [comment]
哈哈，你的信已经进入我的邮箱了，不过我现在还没有看，等我看了就回复你。

**Comment by sameceo** [comment]
哈哈，你的信已经进入我的邮箱了，不过我现在还没有看，等我看了就回复你。
