### ISSUE TITLE
部分路径中带有冒号，无法clone

### ISSUE THREAD

**Issue by Kingong** [okxlin/appstore#1333]
部分路径中带有冒号，无法clone
![image](https://github.com/okxlin/appstore/assets/32238880/5e682ea2-1ccf-41cd-9d0e-418f10f23ce5)

**Comment by okxlin** [comment]
无法git clone?

Windows下可能有文件夹名长度限制，

Linux下正常。

我有空闲时修改一下，这个是自动更新机器人搞的问题。

1Panel的话，镜像名称过长又不加引号确实是会部署失败。

**Comment by okxlin** [comment]
已修正
