### ISSUE TITLE
求添加chatgpt-on-wechat

### ISSUE THREAD

**Issue by Tacit-git** [okxlin/appstore#1429]
求添加chatgpt-on-wechat

https://github.com/zhayujie/chatgpt-on-wechat

微信、飞书、钉钉

**Comment by makaspacex** [comment]
着急的话就比着葫芦画瓢呗，其实很简单的。

**Comment by okxlin** [comment]
可以试试，没有用映射json配置文件的方式，用的1Panel可视化直接设置环境变量。

***
## 注意

**由于`1Panel`自动生成的`.env`文件里的引号为双引号，直接部署会出现异常，**

**需要手动修改一下，将产生异常的行，最外面的双引号修改为单引号，重建应用即可。**

如

```
GROUP_CHAT_IN_ONE_SESSION='["ChatGPT测试群"]'
GROUP_NAME_WHITE_LIST='["ChatGPT测试群", "ChatGPT测试群2"]'
IMAGE_CREATE_PREFIX='["画", "看", "找"]'
SINGLE_CHAT_PREFIX='["bot", "@bot"]'
```

文件路径，按需修改
```
/opt/1panel/apps/local/chatgpt-on-wechat/chatgpt-on-wechat/.env
```
