### ISSUE TITLE
安装雷池 docker-compose.yml: `version` is obsolete"

### ISSUE THREAD

**Issue by 21307369** [okxlin/appstore#1445]
level=warning msg="/opt/1panel/apps/local/safeline/localsafeline/docker-compose.yml: `version` is obsolete"

**Comment by okxlin** [comment]
新版本docker-compose 的特性，废弃了版本指定，只是日志警告，实际当前阶段无影响。

等后面有空把所有`docker-compose.yml`里的`version`设置都删了

**Comment by okxlin** [comment]
已经删除相关`version`设置

https://github.com/okxlin/appstore/commit/5de86718446d78619d53b88af2a1fb04fa24d58d
