### ISSUE TITLE
雷池从5.6.1升级 newnet-6.0.1 创建网络失败

### ISSUE THREAD

**Issue by penguin806** [okxlin/appstore#1469]
Network safeline-ce  Creating
 Network safeline-ce  Error
failed to create network safeline-ce: Error response from daemon: Pool overlaps with other one on this address space
  
[2024-06-01 15:04:51] [INFO] 应用  localsafeline 回滚 

![image](https://github.com/okxlin/appstore/assets/8597729/7f0fe3bd-f64d-48ef-a61a-5562887cf90a)

升级时无法选择其他版本

**Comment by okxlin** [comment]
哦哦，官方论坛的帖子是你发的呀，正好都回复了，

官方这个检测不到更新我也不知道是为什么……我去问问

***
新创建网络网络失败了，重启docker服务再试试或可以解决。

之前安装的版本是什么，更新选择的版本最好也是那个系列的。

如果商店实在更新不上来，去找到新版本的docker-compose.yml文件，

直接应用编辑页面>高级设置>编辑compose文件，然后复制粘贴过去，保存，重建了应用就行了

**Comment by penguin806** [comment]
好的，谢谢大佬，官方论坛的帖子不是我 :joy_cat:
