### ISSUE TITLE
myip端口应该更新了

### ISSUE THREAD

**Issue by astych666** [okxlin/appstore#1470]
[原仓库](https://github.com/jason5ng32/MyIP/commit/d2073ccdfe398fbb533a982d5bdb0472beef949e#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557)已经将端口修改为18966，大佬你这个myip的docker-compose文件还是原来的8966，大佬看到了麻烦更新一下

**Comment by okxlin** [comment]
好的收到，谢谢提醒
