### ISSUE TITLE
遥遥领先

### ISSUE THREAD

**Issue by Satisfy8375** [okxlin/appstore#175]

**Comment by okxlin** [comment]
![image](https://github.com/okxlin/appstore/assets/61420215/26c518e0-5b48-4fab-af68-fe8049f4c082)

**Comment by Satisfy8375** [comment]
> ![image](https://user-images.githubusercontent.com/61420215/261049615-26c518e0-5b48-4fab-af68-fe8049f4c082.png)

大佬，有空可以关注一下，seatable（多维数据表格）和seafile（支持webdav的同步网盘）这2个项目，都有开源社区版，也支持docker部署，看能不能整上。

**Comment by okxlin** [comment]
收到，用空看看

**Comment by Satisfy8375** [comment]
> 收到，用空看看

哈哈，还有个思源笔记也不错

**Comment by okxlin** [comment]
- seatable
- seafile
- 思源笔记

已上，不过感觉`seafile`和`seatable`都不是很好用的样子，🤪

**Comment by Satisfy8375** [comment]
> * seatable
> * seafile
> * 思源笔记
> 
> 已上，不过感觉`seafile`和`seatable`都不是很好用的样子，🤪

遥遥领先

**Comment by Satisfy8375** [comment]
> * seatable
> * seafile
> * 思源笔记
> 
> 已上，不过感觉`seafile`和`seatable`都不是很好用的样子，🤪

没找到，是要重新更新一次应用吗

**Comment by okxlin** [comment]
> > * seatable
> > * seafile
> > * 思源笔记
> > 
> > 已上，不过感觉`seafile`和`seatable`都不是很好用的样子，🤪
> 
> 没找到，是要重新更新一次应用吗

重新导入，然后商店那边更新应用列表
