### ISSUE TITLE
遥遥领先+1 

### ISSUE THREAD

**Issue by xkloveme** [okxlin/appstore#182]
希望可以添加国产的数据库数据结构（schema）管理工具 bytebase 也是支持docker 部署的，https://www.bytebase.com/
，基于 Web 界面
![image](https://github.com/okxlin/appstore/assets/29595042/3aa71c3f-26b5-455c-9cc3-8bac39a089f5)

**Comment by xkloveme** [comment]
再推荐一个bbs应用 https://docs.fresns.cn/
Fresns
一款免费开源的社交网络服务软件

专为跨平台而打造的通用型社区产品，支持灵活多样的内容形态，可以满足多种运营场景，符合时代潮流，更开放且更易于二次开发
![image](https://github.com/okxlin/appstore/assets/29595042/542a1189-1695-4a0f-8c21-856de8f50814)

**Comment by okxlin** [comment]
有空看看
