### ISSUE TITLE
请求添加：MiGPT GUI；为家里的小爱音箱增加AI语音模型支持

### ISSUE THREAD

**Issue by NJYZ-96** [okxlin/appstore#1836]
主项目是[mi-gpt](https://github.com/idootop/mi-gpt) ；将小爱音箱接入 ChatGPT 和豆包，改造成你的专属语音助手。但是没有图形化界面，配置不便，修改设置也不方便；这个在[appstore](https://github.com/okxlin/appstore)商店已经有了。

请求添加[migpt-cli](https://github.com/lmk123/migpt-cli) ；这个是为 [MiGPT](https://github.com/idootop/mi-gpt/) 提供图形化操作界面的；官网是https://migptgui.com/ ；有现成的[Docker镜像](https://migptgui.com/docs/intro/docker)；
项目星星虽然不多，但开发者是浏览器扩展划词翻译的开发者，项目也得到了主项目[mi-gpt](https://github.com/idootop/mi-gpt)的推荐；

**Comment by okxlin** [comment]
已添加
