### ISSUE TITLE
错误反馈：迅雷插件中compose 文件中容器端口映射设置错误

### ISSUE THREAD

**Issue by NJYZ-96** [okxlin/appstore#1849]
源文件：
ports:  
  - "${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}"
  - 
  
  - 
  - 应该改为      - "${PANEL_APP_PORT_HTTP}:2345"

**Comment by okxlin** [comment]
感谢反馈，是原项目的变量命名更改了，所以环境变量设置失效。请等待后续更新

**Comment by okxlin** [comment]
已经重新适配，建议卸载原有的，重新安装
