### ISSUE TITLE
add picx 

### ISSUE THREAD

**Issue by dc932dc** [okxlin/appstore#203]
@okxlin Request to add：

- [x] https://github.com/srcrs/rss-reader
- [x] https://github.com/XPoet/picx

![无标题](https://github.com/okxlin/appstore/assets/46415893/382fe00a-63e9-41a9-9587-dbef5724bb73)

**Comment by cyolc932** [comment]
@okxlin 申请添加[zedeusnitter Alternative Twitter front-end](https://github.com/zedeus/nitter)

**Comment by okxlin** [comment]
收到，有空看看哈

**Comment by dc932dc** [comment]
> 收到，有空看看哈

@okxlin 老哥
7. https://github.com/XPoet/picx 
您方便让第七点的Picx项目优先提上吗。

起因：[永不失效！整了个狠活，自制工具解锁笔记全新方式](https://mp.weixin.qq.com/s/daUrBWaqrSgMUlYVTi9KTw)
（文章存档：[永不失效！整了个狠活，自制工具解锁笔记全新方式 (2023_8_27 10_56_32).zip](https://github.com/okxlin/appstore/files/12447139/2023_8_27.10_56_32.zip)）

这篇文章讲了图片永久保存的最佳方案，并非借助网络图床。
而是**压缩为webp格式，然后转为base64编码，并采用了markdown的文末引用写法**。
文章作者虽然推荐了一堆可选工具，但我觉得仍不是最佳选择。
我在众多开源项目中寻到 [picx](https://github.com/XPoet/picx) 的工具箱。
官方给出了自建选择，支持批量处理，很吸引人。
![图片](https://github.com/okxlin/appstore/assets/46415893/c163e330-ce15-482f-a8ec-b4725296d0d5)

对于当下网络环境的各种网络图床并发，也许图片转base64编码会有不一样的使用体验，未来也会慢慢让大多数人接受。

**Comment by okxlin** [comment]
我看了下哈，`picx`作者原项目不推荐自建，而是使用他的服务。

虽然`hub.docker.com`有镜像，但是是否可信不可知。

如果只是需要图片压缩和转`base64`，可以尝试搭配以下方式使用

- https://squoosh.app/ 谷歌出品离线压缩
- easyimage2 应用库有，可以上传图片转换成其他格式
- it-tools  应用库有，强大的工具箱，有图片与`base64`互转的功能。

**Comment by dc932dc** [comment]
> 我看了下哈，`picx`作者原项目不推荐自建，而是使用他的服务。
> 
> 虽然`hub.docker.com`有镜像，但是是否可信不可知。
> 
> 如果只是需要图片压缩和转`base64`，可以尝试搭配以下方式使用
> 
>     * https://squoosh.app/ 谷歌出品离线压缩
> 
>     * easyimage2 应用库有，可以上传图片转换成其他格式
> 
>     * it-tools  应用库有，强大的工具箱，有图片与`base64`互转的功能。

这个其实是静态的 那个gh-pages分支拉下来就能部署
https://github.com/XPoet/picx/tree/gh-pages

**Comment by okxlin** [comment]
> > 我看了下哈，`picx`作者原项目不推荐自建，而是使用他的服务。
> > 虽然`hub.docker.com`有镜像，但是是否可信不可知。
> > 如果只是需要图片压缩和转`base64`，可以尝试搭配以下方式使用
> > ```
> > * https://squoosh.app/ 谷歌出品离线压缩
> > 
> > * easyimage2 应用库有，可以上传图片转换成其他格式
> > 
> > * it-tools  应用库有，强大的工具箱，有图片与`base64`互转的功能。
> > ```
> 
> 这个其实是静态的 那个gh-pages分支拉下来就能部署 https://github.com/XPoet/picx/tree/gh-pages

哈哈，那是方便，纯静态直接新建站点不是挺好的，都不用折腾。

行吧，我看看。

另外[v2board](https://github.com/v2board/v2board)这种，你懂的原因，可能暂时我不会上的哈。

[rss-reader](https://github.com/srcrs/rss-reader)应用库里已经有了

**Comment by okxlin** [comment]
`picx`已添加

![image](https://github.com/okxlin/appstore/assets/61420215/4e2bb3b6-4cf1-45e5-967e-f6e73ec72bce)
