### ISSUE TITLE
lucky添加个建站标签

### ISSUE THREAD

**Issue by gracelsy** [okxlin/appstore#2155]
lucky添加个建站标签

**Comment by okxlin** [comment]
lucky算是工具应用吧，就没归类到建站标签了。

是为了一键部署使用吗。实际上我个人并不怎么推荐直接网站那边添加一键部署网站，后续不好切换修改。

还是添加一个静态网站后，再修改一下反向代理来得方便

**Comment by gracelsy** [comment]
想使用1panel的waf

**Comment by okxlin** [comment]
WAF和应用分类没关系吧？
