### ISSUE TITLE
应用集在本地未显示

### ISSUE THREAD

**Issue by dickpy** [okxlin/appstore#2157]
应用集在本地未显示

![image](https://github.com/user-attachments/assets/a50407b1-95d8-4a19-b4f2-1df5ed9da08c)

操作步骤：
wget -P /workspace/1panel/resource/apps/local https://mirror.ghproxy.com/https://github.com/okxlin/appstore/archive/refs/heads/localApps.zip

unzip -o -d /workspace/1panel/resource/apps/local/ /workspace/1panel/resource/apps/local/localApps.zip

cp -rf /workspace/1panel/resource/apps/local/appstore-localApps/apps/*  /workspace/1panel/resource/apps/local/

rm -r /workspace/1panel/resource/apps/local/appstore-localApps

rm /workspace/1panel/resource/apps/local/localApps.zip

**Comment by okxlin** [comment]
看看文件夹路径对不对，要在1panel数据的目录文件夹下
