### ISSUE TITLE
安装的脚本中国内的github镜像地址需要更新

### ISSUE THREAD

**Issue by chivehao** [okxlin/appstore#2327]
<https://ghp.ci/>

>主域名 ghproxy.com 已喜提 GFW，请访问和收藏 ghp.ci 分站

**Comment by okxlin** [comment]
谢谢，脚本提到的这个主域名之前就被墙了，二级域名还是好的，原公益加速站点也有说明。

就暂时不修改了哈。

![image](https://github.com/user-attachments/assets/eb01f32d-6659-4551-b399-eefc3cb3493e)
