### ISSUE TITLE
根據長亭雷池（chaitin/safeline）官方公佈的 7.0.0 更新日誌，chaitin/safeline-bridge 已被移除，取而代之是合併至 chaitin/safeline-mgt 容器

### ISSUE THREAD

**Issue by TW527E** [okxlin/appstore#2398]
根據長亭雷池（chaitin/safeline）官方公佈的 7.0.0 更新日誌裡的優化項目中，chaitin/safeline-bridge 容器已被移除，取而代之是合併至 chaitin/safeline-mgt 容器。
因此本項目應將 chaitin/safeline-bridge 移除，而非更新至 7.0.0。

**Comment by okxlin** [comment]
感谢提醒，已经修改

**Comment by TW527E** [comment]
咳咳... safeline-mgt 裡面的 volumes 似乎還有多上這一條w
`            - /var/run:/app/run`
這個應該是把 bridge 整和進 mgt 加的
因為這條原本在 bridge 那
雖然不加上它也能跑 但是我也不知道會出什麼問題（

**Comment by okxlin** [comment]
谢谢提醒，哈哈，大半夜搞迷迷糊糊的，

https://github.com/chaitin/SafeLine/commit/82a2e4473a1923527a2bf14d2fbc052b2757bc79

根据官方修改记录，已修改

**Comment by TW527E** [comment]
恩恩ww 辛苦啦w
