### ISSUE TITLE
[BUG]mTab程序使用应用商店无法构建

### ISSUE THREAD

**Issue by Seameee** [okxlin/appstore#2401]
经测试使用应用商店构建时提示以下错误：
`stderr: localmtab Pulling localmtab Error manifest for itushan/mtab:2.2.0 not found: manifest unknown: manifest unknown Error response from daemon: manifest for itushan/mtab:2.2.0 not found: manifest unknown: manifest unknown`
使用mTab官方提供的[docker-compose](https://www.mtab.cc/docker-compose.yaml)文件可以正常部署，查询dockerhub发现应用商店使用的2.2.0版本已经删除，期待修复更新版本

**Comment by okxlin** [comment]
重新拉取一下最新的库

仓库的镜像版本早些就更新了

https://github.com/okxlin/appstore/tree/localApps/apps/mtab
