### ISSUE TITLE
可以加这个EasyImage2.0 简单图床进去吗？

### ISSUE THREAD

**Issue by wxhdrsa7** [okxlin/appstore#256]
https://github.com/icret/EasyImages2.0

**Comment by okxlin** [comment]
这个很早就上了呀

![image](https://github.com/okxlin/appstore/assets/61420215/7e397152-f65c-4300-a324-17d68b90cc61)

**Comment by wxhdrsa7** [comment]
抱歉，我的问题，昨天没有看到
