### ISSUE TITLE
考虑添加Node环境嘛

### ISSUE THREAD

**Issue by Dacong-wu** [okxlin/appstore#259]

**Comment by okxlin** [comment]
可视化的得官方面板支持呀，镜像类型的node环境和宿主机直接安装，大差不差。

如果只是需要node应用这种，可以上，

然后后期自己写dockerfile，或者进node容器配置好后自己存为新镜像等等。

**Comment by wanghe-fit2cloud** [comment]
1Panel 最新版本已经支持创建 Node.js 运行环境。
