### ISSUE TITLE
在飞牛系统中安装好第三方库，应用商店中没有第三方应用

### ISSUE THREAD

**Issue by sunkolin** [okxlin/appstore#2771]
在飞牛系统中安装好第三方库，应用商店中没有第三方应用

**Comment by okxlin** [comment]
https://github.com/okxlin/appstore#2-%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F

**默认`1Panel`安装在`/opt/`路径下，如果不是按需修改以下。**

飞牛的路径你要按需修改
