### ISSUE TITLE
开源的书签（导航）管理程序TwoNav

### ISSUE THREAD

**Issue by wxhdrsa7** [okxlin/appstore#282]
TwoNav 是一款开源的书签（导航）管理程序，界面简洁，安装简单，使用方便，基础功能免费。TwoNav可帮助你将浏览器书签集中式管理，解决跨设备、跨平台、跨浏览器之间同步和访问困难问题，做到一处部署，随处访问。
https://github.com/tznb1/TwoNav

**Comment by okxlin** [comment]
之前有做过，但是没传上来，感觉不是很好

默认一样简陋，主题照样收费的，和`onenav差不多`

**Comment by wxhdrsa7** [comment]
感觉比onenav好一些，能不能安排上

**Comment by okxlin** [comment]
已添加
