### ISSUE TITLE
我对docker不熟悉，雷池配置是不是有问题？少Postgres用户名

### ISSUE THREAD

**Issue by github-zhanglei** [okxlin/appstore#387]
![image](https://github.com/okxlin/appstore/assets/47292701/94a71ee8-33f3-4194-b56e-52d7ca8d849f)

**Comment by okxlin** [comment]
雷池官方的相关配置是写死的，不需要手动设置其他。可以查看`docker-compose.yml`文件获取细节

**Comment by github-zhanglei** [comment]
安装的时候自动获取不到postgres数据库密码，但这个又是必填项

**Comment by okxlin** [comment]
> 安装的时候自动获取不到postgres数据库密码，但这个又是必填项

就是新建的时候填postgre密码就好了，会自动创建数据库

**Comment by okxlin** [comment]
[1Panel安装长亭雷池WAF的教程(1Panel-installation-tutorial-for-Chaitin-Safeline-WAF).md](https://file.toolman.me/odc/File/OpenSource/1Panel/1Panel%E5%AE%89%E8%A3%85%E9%95%BF%E4%BA%AD%E9%9B%B7%E6%B1%A0WAF%E7%9A%84%E6%95%99%E7%A8%8B(1Panel-installation-tutorial-for-Chaitin-Safeline-WAF).md)

**Comment by github-zhanglei** [comment]
![image](https://github.com/okxlin/appstore/assets/47292701/e7d8f62f-cc43-477a-bec1-96079c2e4970)
会有报错，一会儿我在测试下官方一键命令，看看是不是也有这种情况

**Comment by okxlin** [comment]
查看编排的多个容器运行是否异常就知道了。

我创建时没遇到相关问题

**Comment by github-zhanglei** [comment]
官方一键命令执行没问题；应以同步后显示异常，
![image](https://github.com/okxlin/appstore/assets/47292701/8c3c2bbf-b018-44d1-9563-a930b79d684e)
![image](https://github.com/okxlin/appstore/assets/47292701/50776249-f9c9-4d99-8535-b3fb4b238c8e)
![image](https://github.com/okxlin/appstore/assets/47292701/ef1e9439-6259-4dd3-b758-6ce5d9f0119c)

**Comment by okxlin** [comment]
看了下是新版本api容器有引入使用redis，所以这个api容器里的程序会有异常。

可以删除重建或者复制粘贴新的`docker-compose.yml`然后重建。

另外看了下新的官方配置，tengine也使用redis了，后期适配我可能会需要将redis独立出来了。

**Comment by github-zhanglei** [comment]
![image](https://github.com/okxlin/appstore/assets/47292701/0a11fc1a-8098-4700-b2bb-4adee96542d7)
应用同步后显示异常；进入后台没有报错https://github.com/okxlin/appstore/issues/387#issuecomment-1759452316；

**Comment by okxlin** [comment]
是这样，新版1panel似乎有问题，不止雷池这个应用状态检测异常，我和官方人员沟通过了，等待回应吧

**Comment by okxlin** [comment]
# 更新通告

## 1Panel第三方应用库-长亭雷池(SafeLine WAF)编排已经重新构建


**`3.10.1`** 版本开始，redis 不再使用应用商店安装，而由编排文件创建。

低于此版本的更新到此版本，需要编辑并重建应用。


- 1. 进入已安装应用界面。

- 2. 点击长亭雷池(SafeLine WAF)应用项下的`“参数”`，点击`“编辑”`。

- 3. 然后填写redis密码，端口6379不能变，并 **一定要将redis服务填写为“safeline-redis”**。

- 4. 然后勾选`“高级设置”`，勾选`“编辑compose文件”`。

- 5. 获取更新后的`docker-compose.yml`，查看附录链接。

- 6. 根据自己安装的版本，找到对应的 `docker-compose.yml` 文件，复制文件内容并完全粘贴替换填写框里的内容。

- 7. 最后点击`“确定”`重建应用。

- 8. 以防以后需要应用备份还原，建议也将应用目录下的`data.yml`和`docker-compose.yml`文件做覆盖修改。


### 附录

- https://ghproxy.com/https://github.com/okxlin/appstore/archive/refs/heads/localApps.zip

- https://gh-proxy.com/https://github.com/okxlin/appstore/archive/refs/heads/localApps.zip

- https://github.com/okxlin/appstore/tree/localApps/apps/safeline
