### ISSUE TITLE
请求将meowfacts部署加入

### ISSUE THREAD

**Issue by jerryyang-git** [okxlin/appstore#39]
项目地址：https://github.com/wh-iterabb-it/meowfacts

> 这类小项目感觉在 1panel 提 issues 不太好，所以就来这了 ┻┳|･ω･)

**Comment by okxlin** [comment]
很遗憾，面板目前对于端口批量映射存在问题。

![image](https://github.com/okxlin/appstore/assets/61420215/ee93e747-4492-4666-854d-9fffaedaa975)


建议从源码搭建。

```shell
# 创建目录
mkdir -p /opt/1panel/apps/local/meowfacts/meowfacts/data

# 克隆代码
git clone https://github.com/wh-iterabb-it/meowfacts /opt/1panel/apps/local/meowfacts/meowfacts/data

# 切换到目录
cd /opt/1panel/apps/local/meowfacts/meowfacts/data

# 构建镜像
docker build -t meowfacts:latest .

# 切换到另一个目录
cd /opt/1panel/apps/local/meowfacts/meowfacts/

# 运行容器
docker run -d \
    --name=meowfacts \
    --network 1panel-network \
    --restart always \
    -p 3000-5001:3000-5001 \
    meowfacts:latest
```

这个项目看`Dockerfile`隐射端口有点多，但是看容器日志监听了`5000`端口的样子，建议试试。

另外，从源码编译的应用原则上不怎么想添加进仓库，维护比较麻烦，最好是有现成镜像的。

需要前期源码编译的，或者在Dockerfile写下载源码，比较折腾。😂

以下是个`Dockerfile`里写下载源码的例子
```shell
FROM node:16-alpine

# 安装 git，创建工作目录，并克隆代码
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh && \
    mkdir -p /usr/src/app && \
    git clone https://github.com/wh-iterabb-it/meowfacts /usr/src/app

# 切换到工作目录
WORKDIR /usr/src/app

# 安装 Node.js 依赖
RUN npm install

# 暴露服务器端口
EXPOSE 3000-5001

# 启动应用程序
CMD ["npm", "start"]

```

**Comment by jerryyang-git** [comment]
> 

好的，非常感谢

我尝试从源码搭建，但我发现在我使用下方代码运行这个容器时，我的服务器（E5 2H 2G）占用很大，过了一会这个容器状态为`Created`，想询问下这个占用是不是很大，服务器内存不够容器被 kill 了

```
# 运行容器
docker run -d \
    --name=meowfacts \
    --network 1panel-network \
    --restart always \
    -p 3000-5001:3000-5001 \
    meowfacts:latest
```

![image](https://github.com/okxlin/appstore/assets/60727068/23c5366c-2a36-4131-9f82-1e875c2fa994)

**Comment by okxlin** [comment]
> > 很遗憾，面板目前对于端口批量映射存在问题。
> > ![image](https://user-images.githubusercontent.com/61420215/251978218-ee93e747-4492-4666-854d-9fffaedaa975.png)
> > 建议从源码搭建。
> > ```shell
> > # 创建目录
> > mkdir -p /opt/1panel/apps/local/meowfacts/meowfacts/data
> > 
> > # 克隆代码
> > git clone https://github.com/wh-iterabb-it/meowfacts /opt/1panel/apps/local/meowfacts/meowfacts/data
> > 
> > # 切换到目录
> > cd /opt/1panel/apps/local/meowfacts/meowfacts/data
> > 
> > # 构建镜像
> > docker build -t meowfacts:latest .
> > 
> > # 切换到另一个目录
> > cd /opt/1panel/apps/local/meowfacts/meowfacts/
> > 
> > # 运行容器
> > docker run -d \
> >     --name=meowfacts \
> >     --network 1panel-network \
> >     --restart always \
> >     -p 3000-5001:3000-5001 \
> >     meowfacts:latest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个项目看`Dockerfile`隐射端口有点多，但是看容器日志监听了`5000`端口的样子，建议试试。
> > 另外，从源码编译的应用原则上不怎么想添加进仓库，维护比较麻烦，最好是有现成镜像的。
> > 需要前期源码编译的，或者在Dockerfile写下载源码，比较折腾。😂
> > 以下是个`Dockerfile`里写下载源码的例子
> > ```shell
> > FROM node:16-alpine
> > 
> > # 安装 git，创建工作目录，并克隆代码
> > RUN apk update && apk upgrade && \
> >     apk add --no-cache bash git openssh && \
> >     mkdir -p /usr/src/app && \
> >     git clone https://github.com/wh-iterabb-it/meowfacts /usr/src/app
> > 
> > # 切换到工作目录
> > WORKDIR /usr/src/app
> > 
> > # 安装 Node.js 依赖
> > RUN npm install
> > 
> > # 暴露服务器端口
> > EXPOSE 3000-5001
> > 
> > # 启动应用程序
> > CMD ["npm", "start"]
> > ```
> 
> 好的，非常感谢
> 
> 我尝试从源码搭建，但我发现在我使用下方代码运行这个容器时，我的服务器（E5 2H 2G）占用很大，过了一会这个容器状态为`Created`，想询问下这个占用是不是很大，服务器内存不够容器被 kill 了
> 
> ```
> # 运行容器
> docker run -d \
>     --name=meowfacts \
>     --network 1panel-network \
>     --restart always \
>     -p 3000-5001:3000-5001 \
>     meowfacts:latest
> ```
> 
> ![image](https://user-images.githubusercontent.com/60727068/252000855-23c5366c-2a36-4131-9f82-1e875c2fa994.png)

端口映射太多了，卡死了，

或者可以改为host网络模式跑，需要注意安全与端口是否冲突问题
```
docker run -d \
    --name=meowfacts \
    --network host \
    --restart always \
    meowfacts:latest
```

其实我也比较奇怪为啥要这么多端口来着……

**Comment by jerryyang-git** [comment]
> > > 很遗憾，面板目前对于端口批量映射存在问题。
> > > ![image](https://user-images.githubusercontent.com/61420215/251978218-ee93e747-4492-4666-854d-9fffaedaa975.png)
> > > 建议从源码搭建。
> > > ```shell
> > > # 创建目录
> > > mkdir -p /opt/1panel/apps/local/meowfacts/meowfacts/data
> > > 
> > > # 克隆代码
> > > git clone https://github.com/wh-iterabb-it/meowfacts /opt/1panel/apps/local/meowfacts/meowfacts/data
> > > 
> > > # 切换到目录
> > > cd /opt/1panel/apps/local/meowfacts/meowfacts/data
> > > 
> > > # 构建镜像
> > > docker build -t meowfacts:latest .
> > > 
> > > # 切换到另一个目录
> > > cd /opt/1panel/apps/local/meowfacts/meowfacts/
> > > 
> > > # 运行容器
> > > docker run -d \
> > >     --name=meowfacts \
> > >     --network 1panel-network \
> > >     --restart always \
> > >     -p 3000-5001:3000-5001 \
> > >     meowfacts:latest
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这个项目看`Dockerfile`隐射端口有点多，但是看容器日志监听了`5000`端口的样子，建议试试。
> > > 另外，从源码编译的应用原则上不怎么想添加进仓库，维护比较麻烦，最好是有现成镜像的。
> > > 需要前期源码编译的，或者在Dockerfile写下载源码，比较折腾。😂
> > > 以下是个`Dockerfile`里写下载源码的例子
> > > ```shell
> > > FROM node:16-alpine
> > > 
> > > # 安装 git，创建工作目录，并克隆代码
> > > RUN apk update && apk upgrade && \
> > >     apk add --no-cache bash git openssh && \
> > >     mkdir -p /usr/src/app && \
> > >     git clone https://github.com/wh-iterabb-it/meowfacts /usr/src/app
> > > 
> > > # 切换到工作目录
> > > WORKDIR /usr/src/app
> > > 
> > > # 安装 Node.js 依赖
> > > RUN npm install
> > > 
> > > # 暴露服务器端口
> > > EXPOSE 3000-5001
> > > 
> > > # 启动应用程序
> > > CMD ["npm", "start"]
> > > ```
> > 
> > 
> > 好的，非常感谢
> > 我尝试从源码搭建，但我发现在我使用下方代码运行这个容器时，我的服务器（E5 2H 2G）占用很大，过了一会这个容器状态为`Created`，想询问下这个占用是不是很大，服务器内存不够容器被 kill 了
> > ```
> > # 运行容器
> > docker run -d \
> >     --name=meowfacts \
> >     --network 1panel-network \
> >     --restart always \
> >     -p 3000-5001:3000-5001 \
> >     meowfacts:latest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/60727068/252000855-23c5366c-2a36-4131-9f82-1e875c2fa994.png)
> 
> 端口映射太多了，卡死了，
> 
> 或者可以改为host网络模式跑，需要注意安全与端口是否冲突问题
> 
> ```
> docker run -d \
>     --name=meowfacts \
>     --network host \
>     --restart always \
>     meowfacts:latest
> ```
> 
> 其实我也比较奇怪为啥要这么多端口来着……


好的，非常感谢，运行成功了，我尝试只开 5000 端口使用，其他端口目前不知道是干什么的(¦3[▓▓]

**Comment by jerryyang-git** [comment]
> 另外，从源码编译的应用原则上不怎么想添加进仓库，维护比较麻烦，最好是有现成镜像的。

大佬，我编译了一份上传了 docker，这样可以加吗 (¦3[▓▓]心情简单

Docker地址：https://hub.docker.com/r/jerryyangxyy/meowfacts/tags

**Comment by okxlin** [comment]
> > 另外，从源码编译的应用原则上不怎么想添加进仓库，维护比较麻烦，最好是有现成镜像的。
> 
> 大佬，我编译了一份上传了 docker，这样可以加吗 (¦3[▓▓]心情简单
> 
> Docker地址：https://hub.docker.com/r/jerryyangxyy/meowfacts/tags

好的哈，我待会儿上架一下，还是下源码跑好了。

我又测了下，映射内部`5000`端口就好了。

**Comment by okxlin** [comment]
已上架`meowfacts`

**Comment by jerryyang-git** [comment]
> 已上架`meowfacts`

好的，((ヾ(｡･ω･)ﾉ☆ﾟ+.谢谢啦
