### ISSUE TITLE
https://ghproxy.com代理挂了

### ISSUE THREAD

**Issue by github-zhanglei** [okxlin/appstore#466]
国内还有好用代理没

**Comment by okxlin** [comment]
用gh-proxy，或者用仓库里的gh-proxy项目自建一个

**Comment by okxlin** [comment]
> GitHub加速方式
>> - (本仓库已添加)自建：https://github.com/hunshcn/gh-proxy
>> - ~~https://ghproxy.com~~
>> - https://mirror.ghproxy.com
>> - https://gh-proxy.com
