### ISSUE TITLE
雷池更新到了[3.11.1]  我该如何在面板里更新

### ISSUE THREAD

**Issue by 21307369** [okxlin/appstore#501]
如题 我按照雷池官方文档的方式 
```
bash -c "$(curl -fsSLk https://waf-ce.chaitin.cn/release/latest/upgrade.sh)"
```
[SafeLine] 没有发现位于 /data/1panel/apps/local/safeline/LC/data 的雷池环境

我给整不会了. 我对docker 不太熟悉,我该怎么操作

**Comment by okxlin** [comment]
你用本仓库安装的吧？

如果你有持续拉取本仓库，刷新应用列表后，原则上1panel会提示有新版本更新。

如果不行，就可以编辑应用参数，编辑compose文件，批量替换镜像标签
如这个后面的
```
image: chaitin/safeline-tengine:3.11.1

```

`3.11.1`。

如果是直接装的latest版本的，装个watchtower就可以自动更新了.

雷池官方脚本默认跑的latest版本，且和本仓库配置参数不一致，不能一起用。

**Comment by everydaylove** [comment]
> 你用本仓库安装的吧？
> 
> 如果你有持续拉取本仓库，刷新应用列表后，原则上1panel会提示有新版本更新。
> 
> 如果不行，就可以编辑应用参数，编辑compose文件，批量替换镜像标签 如这个后面的
> 
> ```
> image: chaitin/safeline-tengine:3.11.1
> ```
> 
> `3.11.1`。
> 
> 如果是直接装的latest版本的，装个watchtower就可以自动更新了.
> 
> 雷池官方脚本默认跑的latest版本，且和本仓库配置参数不一致，不能一起用。




通过本仓库安装了雷池，拉取仓库的最新版本后，点击更新应用列表，依然无法在"可升级"里找到雷池。

编辑compose文件替换标签是指换成最新版本号吗？然后重建雷池容器？

**Comment by okxlin** [comment]
对的，把编辑compose那里的文本复制出来到文本编辑软件，然后用ctrl h ，批量替换镜像的版本标签，

再粘贴回去，然后重建即可。

镜像标签可以查看参照这个获取，

- https://hub.docker.com/r/chaitin/safeline-tengine/tags

雷池几个容器的版本号都是一样的

**Comment by 21307369** [comment]
最新版的 好像有问题. 请求的都是502报错

**Comment by okxlin** [comment]
> 最新版的 好像有问题. 请求的都是502报错

https://github.com/okxlin/appstore/issues/561

**Comment by 21307369** [comment]
使用的是新的编排啊 然后一直502  几个都试过了 重装了好几次

**Comment by okxlin** [comment]
> 使用的是新的编排啊 然后一直502 几个都试过了 重装了好几次

你确定用的最新的吗？你参照通告处理一下看看

然后看看容器是否异常

我的没问题呀

![image](https://github.com/okxlin/appstore/assets/61420215/f9d39d76-1edc-4362-8824-89c9275143d5)

**Comment by 21307369** [comment]
![image](https://github.com/okxlin/appstore/assets/47931342/639924a1-7912-4429-adf6-25f017dc9e9c)
新装的 
newnet-latest 和其他的都试过了
都是卸载重装 发现都是502 想退回旧的找不到旧的编排了

**Comment by 21307369** [comment]
1Panel-localsafeline-lu5h-tengine      | 2023/11/26 21:58:29 [91m[ERROR][0m client/secret.go:40 exchange secret error asn1: structure error: tags don't match (16 vs {class:0 tag:28 length:104 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} publicKeyInfo @2
容器里面的错误日志

**Comment by okxlin** [comment]
你是卸载重装?保留的以前数据？数据库信息等对应么，

直接修改compose文件重建不是更好么……

**Comment by 21307369** [comment]
重建后一直502 然后才卸载的 没有保留以前的数据.

**Comment by okxlin** [comment]
> 重建后一直502 然后才卸载的 没有保留以前的数据.

奇怪，我安装一下试试

**Comment by okxlin** [comment]
没有发现问题呀，要不重启一下docker试试？

我更新镜像到最新版本了，你可以重新拉取一下，再试试，应该和镜像版本没关系，我上个版本也是正常的。

![image](https://github.com/okxlin/appstore/assets/61420215/49be47d1-73f0-4854-be9b-df07dca9301b)
![image](https://github.com/okxlin/appstore/assets/61420215/b21d6790-22e7-41d2-a168-6a3d2563ea92)

**Comment by 21307369** [comment]
官方的github 也有这个issues
https://github.com/chaitin/SafeLine/issues/468

**Comment by okxlin** [comment]
# 2023/11/30

# 更新通告

## 1Panel第三方应用库-长亭雷池(SafeLine WAF) 3.14.0版本移除了redis容器，编排需要重新构建

- 1. 进入已安装应用界面。

- 2. 点击长亭雷池(SafeLine WAF)应用项下的`“参数”`，点击`“编辑”`。

- 3. 勾选`“高级设置”`，勾选`“编辑compose文件”`。

- 4. 获取更新后的`docker-compose.yml`，查看附录链接。

- 5. 根据自己安装的版本，找到对应的 `docker-compose.yml` 文件，复制文件内容并完全粘贴替换填写框里的内容。

- 6. 最后点击`“确定”`重建应用。

### 附录

- https://mirror.ghproxy.com/https://github.com/okxlin/appstore/archive/refs/heads/localApps.zip

- https://gh-proxy.com/https://github.com/okxlin/appstore/archive/refs/heads/localApps.zip

- https://github.com/okxlin/appstore/tree/localApps/apps/safeline

**Comment by okxlin** [comment]
看看这个 https://github.com/chaitin/SafeLine/issues/477

**Comment by 21307369** [comment]
兄弟是我建的
