### ISSUE TITLE
雷池重启docker容器IP会发生变化导致无法连接

### ISSUE THREAD

**Issue by freewebcode** [okxlin/appstore#723]
我装的1panel重启docker或者编辑容器IP会发生变化导致无法连接，而docker-compose里连接用的静态ip，还给每个应用都分配了ip，我看没人提问，难道只有我的docker重启ip会变吗？
我每次更新都得修改docker-compose使用别名方式连接！
postgres14升到15数据库也报错了。no actual collation version could be determined，又用回14了

**Comment by okxlin** [comment]
docker-compose指定了静态IP，IP自然就固定了。

然后用本仓库适配的雷池，容器名要固定，

https://github.com/chaitin/SafeLine/issues/477


至于数据库问题，我用15版本很久了，使用倒是很正常。

编排要匹配，雷池经常更改编排文件的。

https://github.com/okxlin/appstore/issues/561

**Comment by okxlin** [comment]
数据库问题，虽然日志报警，但实际好像不会有影响。

可能是之前使用的镜像基础系统不同。

你可以试试将镜像更改为pg的主系列版本，而不是alpine版本。

我已经更新，可以复制重建

……雷池之前4.0 beta用的alpine镜像，还以为可以省点空间了，又给改回去了

**Comment by freewebcode** [comment]
> 数据库问题，虽然日志报警，但实际好像不会有影响。
> 
> 可能是之前使用的镜像基础系统不同。
> 
> 你可以试试将镜像更改为pg的主系列版本，而不是alpine版本。
> 
> 我已经更新，可以复制重建
> 
> ……雷池之前4.0 beta用的alpine镜像，还以为可以省点空间了，又给改回去了

我今天遇到不能切换防护模式的问题，发现mario.yml里面数据库用的safeline-postgres别名连接，我更新了4.0.2顺便把数据库别名从safeline-pg改成了safeline-postgres就好了，不知是不是这个原因

**Comment by okxlin** [comment]
> > 数据库问题，虽然日志报警，但实际好像不会有影响。
> > 可能是之前使用的镜像基础系统不同。
> > 你可以试试将镜像更改为pg的主系列版本，而不是alpine版本。
> > 我已经更新，可以复制重建
> > ……雷池之前4.0 beta用的alpine镜像，还以为可以省点空间了，又给改回去了
> 
> 我今天遇到不能切换防护模式的问题，发现mario.yml里面数据库用的safeline-postgres别名连接，我更新了4.0.2顺便把数据库别名从safeline-pg改成了safeline-postgres就好了，不知是不是这个原因

应该不是，你是不是修改了什么东西。

按照我适配的yml，我的是正常的，可以切换防护模式
