### ISSUE TITLE
国内加速网络地址

### ISSUE THREAD

**Issue by carolcoral** [okxlin/appstore#730]
这个是我自己的国内网络加速地址，可以参考使用：https://gitea.cnkj.site/1Panel/appstore.git

**Comment by okxlin** [comment]
感谢，不过感觉说明文档还是使用已经申明的公开服务相对会好一些。

**Comment by carolcoral** [comment]
> 感谢，不过感觉说明文档还是使用已经申明的公开服务相对会好一些。

这是镜像站，说明文档和当前仓库文档一致

**Comment by okxlin** [comment]
> > 感谢，不过感觉说明文档还是使用已经申明的公开服务相对会好一些。
> 
> 这是镜像站，说明文档和当前仓库文档一致

哈哈，我指的是应用仓库说明文档，优先使用公共服务，就暂不修改了。

**Comment by carolcoral** [comment]
> > > 感谢，不过感觉说明文档还是使用已经申明的公开服务相对会好一些。
> > 
> > 
> > 这是镜像站，说明文档和当前仓库文档一致
> 
> 哈哈，我指的是应用仓库说明文档，优先使用公共服务，就暂不修改了。

👍
