### ISSUE TITLE
希望可以把halo1.5.5添加进去

### ISSUE THREAD

**Issue by minterjia** [okxlin/appstore#797]

**Comment by okxlin** [comment]
这个版本有什么特殊的吗？

**Comment by minterjia** [comment]
用1.5.5习惯了，弄1.6也行

**Comment by okxlin** [comment]
没什么特殊修改的话，直接本地应用halo的文件夹里，复制粘贴一个新文件夹，然后修改`docker-compose.yml`里的`image`镜像设置就好了。

然后更新应用商店，安装的时候选择就好了

**Comment by minterjia** [comment]
没弄出来 不知道咋链接数据库 ---- 回复的原邮件 ***@***.***>发送日期2024年01月24日 22:48 ***@***.***> ***@***.***>***@***.***>主题Re: [okxlin/appstore] 希望可以把halo1.5.5添加进去 (Issue #797)
没什么特殊修改的话，直接本地应用halo的文件夹里，复制粘贴一个新文件夹，然后修改docker-compose.yml里的image镜像设置就好了。
然后更新应用商店，安装的时候选择就好了

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/okxlin/appstore/issues/797#issuecomment-1908282032",
"url": "https://github.com/okxlin/appstore/issues/797#issuecomment-1908282032",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by minterjia** [comment]
没弄出来 不知道咋链接数据库
halo镜像环境1和2有点区别

**Comment by okxlin** [comment]
看了下，是不太一样，建议照着官方文档手动适配一下吧，

几年前的旧版本适配我个人感觉意义不大，就暂不写了。

- https://v1.legacy-docs.halo.run/getting-started/install/other/docker-compose
- https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8
- https://bbs.fit2cloud.com/t/topic/640
