### ISSUE TITLE
添加 DbGate

### ISSUE THREAD

**Issue by wuhang2003** [okxlin/appstore#878]
https://github.com/dbgate/dbgate
数据库管理工具，支持多种数据库的管理，支持 Web 部署且提供了 [Dcoker 镜像](https://hub.docker.com/r/dbgate/dbgate)，也有[对应的 Compose 文件](https://github.com/dbgate/dbgate/blob/master/docker-compose.yaml)参考

**Comment by wuhang2003** [comment]
#880 自己的 issues 自己尝试写 PR 了（

**Comment by okxlin** [comment]
感谢提交，稍等空闲时验证合并
