### ISSUE TITLE
ModStartCMS V7.6.0

### ISSUE THREAD

**Issue by gracelsy** [okxlin/appstore#879]
![QQ截图20240211134528](https://github.com/okxlin/appstore/assets/43689473/dcb070aa-2e7c-44cf-96c6-ff3fac3c5188)
安装后出现问题

**Comment by okxlin** [comment]
文件夹权限原因

![image](https://github.com/okxlin/appstore/assets/61420215/d273abe6-b83f-4105-89e9-6d200264e6bf)

**Comment by gracelsy** [comment]
权限是给的可读写，是不是他的容器有问题啊
&nbsp;


小小粉刷匠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月19日(星期一) 晚上11:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [okxlin/appstore] ModStartCMS V7.6.0 (Issue #879)






文件夹权限原因

Image.png（在网络上查看）

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了线程。消息ID:< Okxlin /应用程序商店/问题/ 879 / ***@***.***和&gt;

**Comment by gracelsy** [comment]
谢谢
