### ISSUE TITLE
[问题]OLS是不是不全

### ISSUE THREAD

**Issue by Felmon** [okxlin/appstore#976]
OLS的路径映射、个别文件地址和[官方的docker](https://github.com/litespeedtech/ols-docker-env/tree/master)似乎不一样，是不是命令行也不一样了
OLS的.env中缺少配置数据库，怎么使用1panel中已安装的mysql应用呢？
大佬，试了好多遍有一些问题，希望大佬能让部署简单点

**Comment by okxlin** [comment]
ols github里的env是设置docker-compose.yml的参数，因为它里头又跑了一个MySQL的容器。

1panel的ols不同，没有塞在一起跑，所以需要在应用商店里安装。

至于如何连接数据库，都是一样的。

具体软件操作需要自行学习解决。
